"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_app.ipynb.

# %% auto 0
__all__ = ['app', 'hello']

# %% ../nbs/00_app.ipynb 3
from flask import Flask

# define the flask object
app = Flask(__name__) 
# The flask object implements a WSGI application and acts as the central object.  

# %% ../nbs/00_app.ipynb 5
@app.route('/hello', methods=['GET']) # define a route
def hello(): # route handler function
    return "Hello World!" # what gets returned when request hits /hello
